-- 1. Tabela de Histórico de Combate
create table if not exists combat_history (
  id bigint generated by default as identity primary key,
  character_id uuid references characters(id) not null,
  mob_id text not null,
  mob_name text,
  duration_seconds int,
  outcome text check (outcome in ('VICTORY', 'DEFEAT', 'FLEE')),
  xp_gained int default 0,
  silver_gained int default 0,
  loot_gained jsonb,
  damage_dealt int,
  damage_taken int,
  occurred_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists combat_history_character_id_idx on combat_history (character_id);

-- 2. Tabela de Histórico de Masmorra
create table if not exists dungeon_history (
  id bigint generated by default as identity primary key,
  character_id uuid references characters(id) not null,
  dungeon_id text not null,
  dungeon_name text,
  tier int,
  wave_reached int,
  max_waves int,
  duration_seconds int,
  outcome text check (outcome in ('COMPLETED', 'FAILED', 'ABANDONED')),
  xp_gained int default 0,
  silver_gained int default 0,
  loot_gained jsonb,
  occurred_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists dungeon_history_character_id_idx on dungeon_history (character_id);

-- 3. Tabela de Sessões de Usuário
CREATE TABLE IF NOT EXISTS user_sessions (
  user_id uuid PRIMARY KEY,
  last_active_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Habilitar leitura para que o front-end possa ler (se necessário) ou apenas permitir escrita da API
ALTER TABLE combat_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE dungeon_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_sessions ENABLE ROW LEVEL SECURITY;

-- Políticas Simples (Ajuste conforme necessidade de segurança real)
-- Permitir que o usuário leia SEU PRÓPRIO histórico
CREATE POLICY "Ler meu combate" ON combat_history FOR SELECT TO authenticated USING (auth.uid() = character_id);
CREATE POLICY "Ler minha dungeon" ON dungeon_history FOR SELECT TO authenticated USING (auth.uid() = character_id);
-- Permitir que o servidor (Service Role) faça tudo (já é padrão, mas bom garantir que não bloqueie nada)
