-- COMPREHENSIVE PRODUCTION SCHEMA CLONE
-- Generated from production_full_schema_detailed.json
-- This script CAN be run manually in the Supabase SQL Editor.

-- 0. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS public."market_buy_orders" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "buyer_id" uuid NOT NULL,
    "buyer_character_id" uuid NOT NULL,
    "buyer_name" text NOT NULL,
    "item_id" text NOT NULL,
    "item_data" jsonb,
    "amount" integer NOT NULL,
    "filled" integer DEFAULT 0,
    "price_per_unit" bigint NOT NULL,
    "status" text DEFAULT 'ACTIVE'::text,
    "created_at" timestamp with time zone DEFAULT now(),
    "expires_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public."market_listings" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "seller_id" uuid NOT NULL,
    "seller_name" text NOT NULL,
    "item_id" text NOT NULL,
    "item_data" jsonb NOT NULL,
    "amount" bigint NOT NULL,
    "price" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "unit_price" bigint
);

CREATE TABLE IF NOT EXISTS public."characters" (
    "id" uuid NOT NULL DEFAULT auth.uid(),
    "user_id" uuid NOT NULL,
    "name" text NOT NULL,
    "state" jsonb DEFAULT '{"silver": 0, "skills": {}, "inventory": {}}'::jsonb,
    "current_activity" jsonb,
    "activity_started_at" timestamp with time zone,
    "dungeon_state" jsonb,
    "last_saved" timestamp with time zone DEFAULT now(),
    "is_admin" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now(),
    "inventory" jsonb DEFAULT '{}'::jsonb,
    "skills" jsonb DEFAULT '{}'::jsonb,
    "equipment" jsonb DEFAULT '{}'::jsonb,
    "info" jsonb DEFAULT '{}'::jsonb,
    "combat" jsonb,
    "dungeon" jsonb,
    "bank" jsonb DEFAULT '{"items": {}, "slots": 10}'::jsonb,
    "settings" jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."user_sessions" (
    "user_id" uuid NOT NULL,
    "last_active_at" timestamp with time zone NOT NULL DEFAULT now(),
    "ip_address" text,
    "player_name" text
);

CREATE TABLE IF NOT EXISTS public."messages" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" uuid NOT NULL,
    "sender_name" text NOT NULL,
    "content" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "channel" text DEFAULT 'GLOBAL'::text
);

CREATE TABLE IF NOT EXISTS public."combat_history" (
    "id" bigint NOT NULL,
    "character_id" uuid NOT NULL,
    "mob_id" text NOT NULL,
    "mob_name" text,
    "duration_seconds" integer,
    "outcome" text,
    "xp_gained" bigint DEFAULT 0,
    "silver_gained" bigint DEFAULT 0,
    "loot_gained" jsonb,
    "damage_dealt" bigint,
    "damage_taken" bigint,
    "occurred_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    "kills" integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public."trade_sessions" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "sender_id" uuid,
    "receiver_id" uuid,
    "sender_offer" jsonb DEFAULT '{"items": [], "silver": 0}'::jsonb,
    "receiver_offer" jsonb DEFAULT '{"items": [], "silver": 0}'::jsonb,
    "sender_accepted" boolean DEFAULT false,
    "receiver_accepted" boolean DEFAULT false,
    "status" text DEFAULT 'PENDING'::text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    "sender_name" text,
    "receiver_name" text
);

CREATE TABLE IF NOT EXISTS public."dungeon_history" (
    "id" bigint NOT NULL,
    "character_id" uuid NOT NULL,
    "dungeon_id" text NOT NULL,
    "dungeon_name" text,
    "tier" integer,
    "wave_reached" integer,
    "max_waves" integer,
    "duration_seconds" bigint,
    "outcome" text,
    "xp_gained" bigint DEFAULT 0,
    "silver_gained" bigint DEFAULT 0,
    "loot_gained" jsonb,
    "occurred_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    "runs_completed" integer DEFAULT 1,
    "total_runs" integer DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public."trade_history" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "trade_id" text,
    "sender_id" uuid NOT NULL,
    "receiver_id" uuid NOT NULL,
    "sender_name" text,
    "receiver_name" text,
    "sender_items" jsonb DEFAULT '[]'::jsonb,
    "sender_silver" bigint DEFAULT 0,
    "sender_tax" bigint DEFAULT 0,
    "receiver_items" jsonb DEFAULT '[]'::jsonb,
    "receiver_silver" bigint DEFAULT 0,
    "receiver_tax" bigint DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."push_subscriptions" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "user_id" uuid,
    "endpoint" text NOT NULL,
    "p256dh" text NOT NULL,
    "auth" text NOT NULL,
    "settings" jsonb DEFAULT '{"daily_spin": true, "guild_task": true, "new_member": true, "world_boss": true, "item_bought": true, "market_sale": true, "hp_recovered": true, "inventory_full": true, "character_death": true, "dungeon_complete": true, "activity_complete": true}'::jsonb,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."daily_rewards" (
    "user_id" uuid NOT NULL,
    "last_spin" timestamp with time zone DEFAULT now(),
    "created_at" timestamp with time zone DEFAULT now(),
    "character_name" text,
    "reward_id" text
);

CREATE TABLE IF NOT EXISTS public."world_boss_attempts" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "character_id" uuid,
    "date" date NOT NULL,
    "damage" bigint NOT NULL DEFAULT 0,
    "claimed" boolean DEFAULT false,
    "created_at" timestamp with time zone DEFAULT now(),
    "player_name" text
);

CREATE TABLE IF NOT EXISTS public."global_stats" (
    "id" text NOT NULL,
    "total_market_tax" bigint DEFAULT 0,
    "updated_at" timestamp with time zone DEFAULT now(),
    "market_tax_total" bigint DEFAULT 0,
    "trade_tax_total" bigint DEFAULT 0,
    "tax_24h_ago" bigint DEFAULT 0,
    "history" jsonb DEFAULT '[]'::jsonb,
    "last_snapshot_at" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public."user_bans" (
    "user_id" uuid NOT NULL,
    "ban_level" integer NOT NULL DEFAULT 1,
    "banned_until" timestamp with time zone,
    "reason" text,
    "updated_at" timestamp with time zone DEFAULT now(),
    "player_name" text,
    "ack" boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public."friends" (
    "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
    "sender_id" uuid NOT NULL,
    "receiver_id" uuid NOT NULL,
    "status" text NOT NULL DEFAULT 'PENDING'::text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    "is_best_friend" boolean DEFAULT false,
    "best_friend_request_sender" uuid,
    "sender_name" text,
    "receiver_name" text
);

CREATE TABLE IF NOT EXISTS public."guild_requests" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "guild_id" uuid,
    "character_id" uuid,
    "status" text NOT NULL DEFAULT 'PENDING'::text,
    "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."guilds" (
    "id" uuid NOT NULL DEFAULT gen_random_uuid(),
    "name" text NOT NULL,
    "tag" text NOT NULL,
    "summary" text,
    "icon" text,
    "icon_color" text,
    "bg_color" text,
    "leader_id" uuid,
    "level" integer DEFAULT 1,
    "xp" bigint DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT now(),
    "country_code" text,
    "roles" jsonb DEFAULT '{"LEADER": {"name": "Leader", "color": "#d4af37", "permissions": ["edit_appearance", "manage_roles", "kick_members", "manage_requests", "change_member_roles", "manage_upgrades"]}, "MEMBER": {"name": "Member", "color": "#808080", "permissions": []}, "OFFICER": {"name": "Co-Leader", "color": "#c0c0c0", "permissions": ["kick_members", "manage_requests", "manage_upgrades"]}}'::jsonb,
    "min_level" integer DEFAULT 1,
    "join_mode" text DEFAULT 'APPLY'::text,
    "bank_silver" bigint DEFAULT 0,
    "bank_items" jsonb DEFAULT '{}'::jsonb,
    "guild_hall_level" integer DEFAULT 0,
    "gathering_xp_level" integer DEFAULT 0,
    "gathering_duplic_level" integer DEFAULT 0,
    "gathering_auto_level" integer DEFAULT 0,
    "refining_xp_level" integer DEFAULT 0,
    "refining_duplic_level" integer DEFAULT 0,
    "refining_effic_level" integer DEFAULT 0,
    "daily_tasks" jsonb DEFAULT '[]'::jsonb,
    "tasks_last_reset" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone,
    "library_level" integer DEFAULT 0,
    "crafting_xp_level" integer DEFAULT 0,
    "crafting_duplic_level" integer DEFAULT 0,
    "crafting_effic_level" integer DEFAULT 0,
    "guild_points" bigint DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public."market_history" (
    "id" bigint NOT NULL,
    "item_id" text NOT NULL,
    "item_data" jsonb NOT NULL,
    "seller_id" uuid NOT NULL,
    "buyer_id" uuid NOT NULL,
    "seller_name" text,
    "buyer_name" text,
    "quantity" bigint NOT NULL,
    "price_total" bigint NOT NULL,
    "price_per_unit" double precision NOT NULL,
    "tax_paid" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    "order_type" text DEFAULT 'SELL_ORDER'::text
);

CREATE TABLE IF NOT EXISTS public."guild_members" (
    "guild_id" uuid,
    "character_id" uuid NOT NULL,
    "role" text NOT NULL DEFAULT 'MEMBER'::text,
    "joined_at" timestamp with time zone DEFAULT now(),
    "donated_xp" bigint DEFAULT 0,
    "donated_silver" bigint DEFAULT 0,
    "donated_items_value" bigint DEFAULT 0
);

-- 2. Create Indexes
CREATE UNIQUE INDEX market_buy_orders_pkey ON public.market_buy_orders USING btree (id);
CREATE INDEX market_buy_orders_status_item_id_idx ON public.market_buy_orders USING btree (status, item_id);
CREATE INDEX market_buy_orders_buyer_id_idx ON public.market_buy_orders USING btree (buyer_id);
CREATE UNIQUE INDEX market_listings_pkey ON public.market_listings USING btree (id);
CREATE INDEX idx_market_listings_unit_price ON public.market_listings USING btree (unit_price);
CREATE UNIQUE INDEX characters_pkey ON public.characters USING btree (id);
CREATE UNIQUE INDEX characters_name_key ON public.characters USING btree (name);
CREATE INDEX idx_characters_active ON public.characters USING btree (id) WHERE (current_activity IS NOT NULL);
CREATE INDEX idx_characters_current_activity ON public.characters USING btree (current_activity) WHERE (current_activity IS NOT NULL);
CREATE INDEX idx_characters_is_admin ON public.characters USING btree (is_admin) WHERE ((is_admin IS NULL) OR (is_admin = false));
CREATE UNIQUE INDEX user_sessions_pkey ON public.user_sessions USING btree (user_id);
CREATE INDEX idx_user_sessions_ip ON public.user_sessions USING btree (ip_address);
CREATE UNIQUE INDEX combat_history_pkey ON public.combat_history USING btree (id);
CREATE INDEX combat_history_character_id_idx ON public.combat_history USING btree (character_id);
CREATE UNIQUE INDEX dungeon_history_pkey ON public.dungeon_history USING btree (id);
CREATE INDEX dungeon_history_character_id_idx ON public.dungeon_history USING btree (character_id);
CREATE UNIQUE INDEX trade_sessions_pkey ON public.trade_sessions USING btree (id);
CREATE INDEX idx_trade_sender ON public.trade_sessions USING btree (sender_id);
CREATE INDEX idx_trade_receiver ON public.trade_sessions USING btree (receiver_id);
CREATE INDEX idx_trade_status ON public.trade_sessions USING btree (status);
CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);
CREATE INDEX idx_messages_channel ON public.messages USING btree (channel);
CREATE UNIQUE INDEX trade_history_pkey ON public.trade_history USING btree (id);
CREATE INDEX idx_trade_history_date ON public.trade_history USING btree (created_at DESC);
CREATE INDEX idx_trade_history_sender ON public.trade_history USING btree (sender_id);
CREATE INDEX idx_trade_history_receiver ON public.trade_history USING btree (receiver_id);
CREATE UNIQUE INDEX push_subscriptions_pkey ON public.push_subscriptions USING btree (id);
CREATE UNIQUE INDEX push_subscriptions_user_id_endpoint_key ON public.push_subscriptions USING btree (user_id, endpoint);
CREATE INDEX idx_push_subs_user ON public.push_subscriptions USING btree (user_id);
CREATE UNIQUE INDEX global_stats_pkey ON public.global_stats USING btree (id);
CREATE UNIQUE INDEX world_boss_attempts_pkey ON public.world_boss_attempts USING btree (id);
CREATE UNIQUE INDEX world_boss_attempts_character_id_date_key ON public.world_boss_attempts USING btree (character_id, date);
CREATE INDEX idx_wb_attempts_date_damage ON public.world_boss_attempts USING btree (date, damage DESC);
CREATE UNIQUE INDEX daily_rewards_pkey ON public.daily_rewards USING btree (user_id);
CREATE UNIQUE INDEX user_bans_pkey ON public.user_bans USING btree (user_id);
CREATE UNIQUE INDEX friends_pkey ON public.friends USING btree (id);
CREATE UNIQUE INDEX unique_friendship ON public.friends USING btree (sender_id, receiver_id);
CREATE INDEX idx_friends_sender ON public.friends USING btree (sender_id);
CREATE INDEX idx_friends_receiver ON public.friends USING btree (receiver_id);
CREATE UNIQUE INDEX guild_requests_pkey ON public.guild_requests USING btree (id);
CREATE UNIQUE INDEX guild_requests_guild_id_character_id_key ON public.guild_requests USING btree (guild_id, character_id);
CREATE INDEX guild_requests_guild_id_idx ON public.guild_requests USING btree (guild_id);
CREATE INDEX guild_requests_char_id_idx ON public.guild_requests USING btree (character_id);
CREATE UNIQUE INDEX market_history_pkey ON public.market_history USING btree (id);
CREATE INDEX market_history_created_at_idx ON public.market_history USING btree (created_at DESC);
CREATE INDEX market_history_item_id_idx ON public.market_history USING btree (item_id);
CREATE INDEX market_history_seller_id_idx ON public.market_history USING btree (seller_id, created_at DESC);
CREATE INDEX market_history_buyer_id_idx ON public.market_history USING btree (buyer_id, created_at DESC);
CREATE INDEX market_history_order_type_idx ON public.market_history USING btree (order_type);
CREATE UNIQUE INDEX guild_members_pkey ON public.guild_members USING btree (character_id);
CREATE INDEX guild_members_guild_id_idx ON public.guild_members USING btree (guild_id);
CREATE UNIQUE INDEX guilds_pkey ON public.guilds USING btree (id);
CREATE UNIQUE INDEX guilds_name_key ON public.guilds USING btree (name);
CREATE UNIQUE INDEX guilds_tag_key ON public.guilds USING btree (tag);
CREATE INDEX guilds_name_idx ON public.guilds USING btree (name);
CREATE INDEX guilds_tag_idx ON public.guilds USING btree (tag);

-- 3. Create Foreign Keys
ALTER TABLE public."guild_requests" 
    ADD CONSTRAINT "guild_requests_guild_id_fkey" 
    FOREIGN KEY ("guild_id") REFERENCES public."guilds"("id") ON DELETE CASCADE;

ALTER TABLE public."trade_sessions" 
    ADD CONSTRAINT "trade_sessions_sender_id_fkey" 
    FOREIGN KEY ("sender_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."trade_sessions" 
    ADD CONSTRAINT "trade_sessions_receiver_id_fkey" 
    FOREIGN KEY ("receiver_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."combat_history" 
    ADD CONSTRAINT "combat_history_character_id_fkey" 
    FOREIGN KEY ("character_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."dungeon_history" 
    ADD CONSTRAINT "dungeon_history_character_id_fkey" 
    FOREIGN KEY ("character_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."world_boss_attempts" 
    ADD CONSTRAINT "world_boss_attempts_character_id_fkey" 
    FOREIGN KEY ("character_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."friends" 
    ADD CONSTRAINT "friends_sender_id_fkey" 
    FOREIGN KEY ("sender_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."friends" 
    ADD CONSTRAINT "friends_receiver_id_fkey" 
    FOREIGN KEY ("receiver_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."friends" 
    ADD CONSTRAINT "friends_best_friend_request_sender_fkey" 
    FOREIGN KEY ("best_friend_request_sender") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."guild_members" 
    ADD CONSTRAINT "guild_members_guild_id_fkey" 
    FOREIGN KEY ("guild_id") REFERENCES public."guilds"("id") ON DELETE CASCADE;

ALTER TABLE public."guild_members" 
    ADD CONSTRAINT "guild_members_character_id_fkey" 
    FOREIGN KEY ("character_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."guild_requests" 
    ADD CONSTRAINT "guild_requests_character_id_fkey" 
    FOREIGN KEY ("character_id") REFERENCES public."characters"("id") ON DELETE CASCADE;

ALTER TABLE public."guilds" 
    ADD CONSTRAINT "guilds_leader_id_fkey" 
    FOREIGN KEY ("leader_id") REFERENCES public."characters"("id") ON DELETE CASCADE;


-- 4. Enable RLS
ALTER TABLE public."market_buy_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."market_listings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."characters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."combat_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."trade_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."dungeon_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."trade_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."push_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."daily_rewards" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."world_boss_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."global_stats" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user_bans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."friends" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."guild_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."guilds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."market_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."guild_members" ENABLE ROW LEVEL SECURITY;
