-- Create the market_history table to track all sales
create table if not exists market_history (
    id bigint generated by default as identity primary key,
    item_id text not null,
    item_data jsonb not null,
    seller_id uuid references auth.users(id) not null,
    buyer_id uuid references auth.users(id) not null,
    seller_name text,
    buyer_name text,
    quantity bigint not null,
    price_total bigint not null,
    price_per_unit float8 not null,
    tax_paid bigint not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for global history (most recent first)
create index if not exists market_history_created_at_idx on market_history (created_at desc);

-- Index for item-specific history (trends)
create index if not exists market_history_item_id_idx on market_history (item_id);

-- Index for personal history (buying/selling)
create index if not exists market_history_seller_id_idx on market_history (seller_id, created_at desc);
create index if not exists market_history_buyer_id_idx on market_history (buyer_id, created_at desc);

-- Add description for introspection
comment on table market_history is 'Historical records of all completed marketplace transactions.';
