-- Create the dungeon_history table
create table if not exists dungeon_history (
  id bigint generated by default as identity primary key,
  character_id uuid references characters(id) not null,
  dungeon_id text not null,
  dungeon_name text,
  tier int,
  wave_reached int,
  max_waves int,
  duration_seconds int,
  outcome text check (outcome in ('COMPLETED', 'FAILED', 'ABANDONED')),
  xp_gained int default 0,
  silver_gained int default 0,
  loot_gained jsonb, -- Array of strings: ["2x T1_IRON", "1x T2_SWORD"]
  occurred_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for querying by character
create index if not exists dungeon_history_character_id_idx on dungeon_history (character_id);
