-- Create the combat_history table
create table if not exists combat_history (
  id bigint generated by default as identity primary key,
  character_id uuid references characters(id) not null,
  mob_id text not null,
  mob_name text,
  duration_seconds int,
  outcome text check (outcome in ('VICTORY', 'DEFEAT', 'FLEE')),
  xp_gained int default 0,
  silver_gained int default 0,
  loot_gained jsonb,
  damage_dealt int,
  damage_taken int,
  occurred_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for querying by character
create index if not exists combat_history_character_id_idx on combat_history (character_id);
