
-- RODE ESTE SQL NO EDITOR SQL DO SEU SUPABASE PARA CORRIGIR O ERRO DE TAREFAS

ALTER TABLE guilds 
ADD COLUMN IF NOT EXISTS library_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS guild_hall_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gathering_xp_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gathering_duplic_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS gathering_auto_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS refining_xp_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS refining_duplic_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS refining_effic_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS crafting_xp_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS crafting_duplic_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS crafting_effic_level INTEGER DEFAULT 0;

-- Opcional: Adicionar colunas de banco de itens e prata se não existirem
ALTER TABLE guilds ADD COLUMN IF NOT EXISTS bank_silver BIGINT DEFAULT 0;
ALTER TABLE guilds ADD COLUMN IF NOT EXISTS bank_items JSONB DEFAULT '{}';
ALTER TABLE guilds ADD COLUMN IF NOT EXISTS guild_points BIGINT DEFAULT 0;
