import fs from 'fs';

const detailedSchema = JSON.parse(fs.readFileSync('production_full_schema_detailed.json', 'utf8'));

let sql = `-- COMPREHENSIVE PRODUCTION SCHEMA CLONE
-- Generated from production_full_schema_detailed.json
-- This script CAN be run manually in the Supabase SQL Editor.

-- 0. Enable Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. Create Tables
`;

// Helper to format default values and handle sequences
function formatDefault(def, colName, tableName) {
    if (!def) return '';
    
    // Handle nextval sequences by converting them to identity or creating the sequence
    if (def.includes('nextval')) {
        return ` GENERATED BY DEFAULT AS IDENTITY`;
    }
    
    return ` DEFAULT ${def}`;
}

// 1. Tables and Columns
for (const [tableName, columns] of Object.entries(detailedSchema.tables)) {
    sql += `CREATE TABLE IF NOT EXISTS public."${tableName}" (\n`;
    const colDefs = columns.map(col => {
        let line = `    "${col.column_name}" ${col.data_type}`;
        if (col.is_nullable === 'NO') line += ' NOT NULL';
        line += formatDefault(col.column_default, col.column_name, tableName);
        return line;
    });
    sql += colDefs.join(',\n');
    sql += `\n);\n\n`;
}

// 2. Indexes
sql += `-- 2. Create Indexes\n`;
for (const idx of detailedSchema.indexes) {
    if (detailedSchema.tables[idx.tablename]) {
        // Skip pkey indexes as they are often created by constraints, but CREATE UNIQUE INDEX is usually fine
        sql += `${idx.indexdef};\n`;
    }
}

// 3. Foreign Keys (applied after all tables exist)
sql += `\n-- 3. Create Foreign Keys\n`;
for (const fk of detailedSchema.foreignKeys) {
    sql += `ALTER TABLE public."${fk.table_name}" \n`;
    sql += `    ADD CONSTRAINT "${fk.table_name}_${fk.column_name}_fkey" \n`;
    sql += `    FOREIGN KEY ("${fk.column_name}") REFERENCES public."${fk.foreign_table_name}"("${fk.foreign_column_name}") ON DELETE CASCADE;\n\n`;
}

// 4. Basic RLS enablement
sql += `\n-- 4. Enable RLS\n`;
for (const tableName of Object.keys(detailedSchema.tables)) {
    sql += `ALTER TABLE public."${tableName}" ENABLE ROW LEVEL SECURITY;\n`;
}

fs.writeFileSync('sql/full_schema_staging.sql', sql);
console.log("SUCCESS: Generated sql/full_schema_staging.sql (Ready for manual run)");
